# Generated by Django 4.0.1 on 2023-02-07 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSTF', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquinas',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='repuestos',
            name='foto',
        ),
    ]
