# Generated by Django 4.0.1 on 2023-02-07 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSTF', '0002_remove_maquinas_foto_remove_repuestos_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manuales',
            name='archivo',
        ),
    ]
